import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';

import { MANIFESTS, parseManifest } from '../server/services/ecosystems.js';
import { assertPackage } from '../server/services/scanShapes.js';

// The manifest table (v2.53.0).
//
// Everything here is about the same failure: a package name or version derived
// wrongly is not a missing answer, it is a WRONG one. OSV replies "no
// vulnerabilities" for a package that does not exist, so a parser bug is
// recorded as a clean app and reads as safety. Each fixture below is a shape
// that produces exactly that if read naively, and the assertions name the false
// clean rather than the diff.
//
// Fixtures are written to disk and read through parseManifest — the production
// entry point — rather than handed to the parsers as strings, because the file
// read, the filename dispatch and the assertPackage sweep are all part of the
// contract.

const DIR = mkdtempSync(join(tmpdir(), 'crane-eco-'));

function fixture(name, contents) {
  const path = join(DIR, name);
  writeFileSync(path, contents);
  return path;
}

/** Every parser's output must be assertPackage-valid; check it at every call. */
function parse(path, entry) {
  const pkgs = parseManifest(path, entry);
  pkgs.forEach((p, i) => assertPackage(p, `${path}[${i}]`));
  return pkgs;
}

const idsOf = (pkgs) => pkgs.map(p => `${p.name}@${p.version}`).sort();

// ---------------------------------------------------------------------------
// the table
// ---------------------------------------------------------------------------

test('the table maps nine manifests onto OSV ecosystem names', () => {
  assert.deepEqual(
    MANIFESTS.map(m => [m.file, m.ecosystem]),
    [
      ['package-lock.json', 'npm'],
      ['yarn.lock', 'npm'],
      ['pnpm-lock.yaml', 'npm'],
      ['composer.lock', 'Packagist'],
      ['go.sum', 'Go'],
      ['Cargo.lock', 'crates.io'],
      ['Gemfile.lock', 'RubyGems'],
      ['poetry.lock', 'PyPI'],
      ['Pipfile.lock', 'PyPI'],
    ],
    'OSV ecosystem names are matched literally by the API — "cargo", "rubygems" or ' +
    '"pypi" are not errors, they return an empty result set, which records every ' +
    'app in that ecosystem as clean');
  for (const m of MANIFESTS) assert.equal(typeof m.parse, 'function', `${m.file} has no parser`);
});

test('PHP is Packagist, capital P, and nothing else', () => {
  // Measured against the live API rather than read off a list:
  //   {name: symfony/http-kernel, ecosystem: Packagist, version: 5.4.10} -> GHSA-h7vf-5wrv-9fhv
  //   {name: symfony/http-kernel, ecosystem: packagist, version: 5.4.10} -> {} (no vulns key)
  // The lowercase spelling is not an error, it is an empty answer, so every PHP
  // app on the box would be recorded clean. 'Packagist' is also the spelling in
  // the OSV schema's own defined-ecosystems list.
  const php = MANIFESTS.find(m => m.file === 'composer.lock');
  assert.equal(php.ecosystem, 'Packagist');
});

test('three manifests share the npm ecosystem, and two share PyPI', () => {
  // The table is keyed by FILE, not by ecosystem, which is what lets a second
  // and third JavaScript package manager be one row each. Order is
  // presentation only — appScan reads every manifest it finds, so a repo
  // holding both a package-lock.json and a yarn.lock is read twice rather than
  // one shadowing the other.
  assert.deepEqual(
    MANIFESTS.filter(m => m.ecosystem === 'npm').map(m => m.file),
    ['package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']);
  assert.deepEqual(
    MANIFESTS.filter(m => m.ecosystem === 'PyPI').map(m => m.file),
    ['poetry.lock', 'Pipfile.lock']);
});

test('parseManifest dispatches on the filename when no row is passed', () => {
  const path = fixture('Cargo.lock', CARGO_LOCK);
  assert.deepEqual(parse(path), parse(path, MANIFESTS.find(m => m.file === 'Cargo.lock')));
});

test('an unrecognised filename throws rather than returning nothing', () => {
  const path = fixture('requirements.txt', 'django>=4.2\nrequests\n');
  assert.throws(() => parseManifest(path), /no parser for requirements.txt/,
    'an unreadable manifest returned a package list. requirements.txt pins nothing — ' +
    'guessing a version from ">=4.2" answers about a release that may not be installed');
});

test('the recorded error names the manifest that failed', () => {
  // An app can have several manifests. "Unexpected token" on its own does not
  // tell the person reading the scan row which file to open.
  const path = fixture('Pipfile.lock', '{ not json');
  assert.throws(() => parseManifest(path), /^Error: Pipfile\.lock: /);
});

// ---------------------------------------------------------------------------
// npm — generated by `npm install --package-lock-only`, not hand-written
// ---------------------------------------------------------------------------
//
// Produced by npm 10 for a root with a workspace, an aliased dependency
// (mylodash@npm:lodash@4.17.15) and a nested duplicate (async pulls its own
// lodash beside the root's lodash@3). Every trap in one real file.
const NPM_LOCK = JSON.stringify({
  name: 'fixture-root',
  version: '1.0.0',
  lockfileVersion: 3,
  requires: true,
  packages: {
    '': {
      name: 'fixture-root',
      version: '1.0.0',
      workspaces: ['packages/*'],
      dependencies: { async: '2.6.4', lodash: '3.10.1', mylodash: 'npm:lodash@4.17.15' },
    },
    'node_modules/@fixture/design-system': { resolved: 'packages/design-system', link: true },
    'node_modules/async': {
      version: '2.6.4',
      resolved: 'https://registry.npmjs.org/async/-/async-2.6.4.tgz',
      license: 'MIT',
      dependencies: { lodash: '^4.17.14' },
    },
    'node_modules/async/node_modules/lodash': {
      version: '4.18.1',
      resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.18.1.tgz',
      license: 'MIT',
    },
    'node_modules/lodash': {
      version: '3.10.1',
      resolved: 'https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz',
      license: 'MIT',
    },
    'node_modules/mylodash': {
      name: 'lodash',
      version: '4.17.15',
      resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz',
      license: 'MIT',
    },
    'packages/design-system': { name: '@fixture/design-system', version: '3.2.1' },
  },
}, null, 2);

test('a real npm lockfile yields only published packages, under their real names', () => {
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.deepEqual(idsOf(pkgs),
    ['async@2.6.4', 'lodash@3.10.1', 'lodash@4.17.15', 'lodash@4.18.1'],
    'the query set is not the published dependency set');
});

test('an aliased dependency is queried under the package name, not the alias', () => {
  // `npm i mylodash@npm:lodash@4.17.15` keys the entry by its INSTALL PATH.
  // OSV has never heard of "mylodash", so it answers clean and a lodash with
  // six advisories against it is recorded green. npm ships aliases itself —
  // string-width-cjs and strip-ansi-cjs arrive through cliui/wrap-ansi — so
  // this is not an exotic case.
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.ok(pkgs.some(p => p.name === 'lodash' && p.version === '4.17.15'),
    'the aliased lodash@4.17.15 was not queried under the name lodash');
  assert.ok(!pkgs.some(p => p.name === 'mylodash'),
    'the alias "mylodash" was sent to OSV — no registry has it, so the answer is a ' +
    'guaranteed false clean for a package with known advisories');
});

test('the root and the workspace member are not dependencies', () => {
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'fixture-root'),
    'the "" entry is the app itself and is published nowhere');
  // "packages/design-system" carries a real version and is NOT under
  // node_modules, so a parser that slices a fixed 13 characters off every key
  // reports a dependency named "esign-system" — plausible enough in a report,
  // and matching nothing in OSV.
  assert.ok(!pkgs.some(p => p.name.includes('design-system')),
    'the workspace member reached the query set');
  assert.ok(!pkgs.some(p => p.name.includes('/') && !p.name.startsWith('@')),
    'a package name still carries a path fragment; only a scoped name may contain a slash');
});

test('a nested dependency is named for the last node_modules segment', () => {
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.ok(pkgs.some(p => p.name === 'lodash' && p.version === '4.18.1'),
    'the nested async/node_modules/lodash was named after its path — "async/lodash" ' +
    'is not a package, so OSV answers "no vulnerabilities"');
});

test('an npm v1 lockfile is an error, not an empty clean scan', () => {
  const path = fixture('package-lock.json',
    JSON.stringify({ lockfileVersion: 1, dependencies: { lodash: { version: '4.17.15' } } }));
  assert.throws(() => parseManifest(path), /lockfileVersion 1/,
    'a v1 lockfile parsed to zero packages instead of throwing, which records a clean ' +
    'bill of health for a file nothing ever read');
});

// ---------------------------------------------------------------------------
// Go
// ---------------------------------------------------------------------------
//
// Real go.sum lines: every module gets a zip hash and a /go.mod hash, module
// paths carry a /vN suffix from v2 on, and versions come in three shapes —
// plain, +incompatible, and a pseudo-version for an untagged commit.
const GO_SUM = `github.com/bytedance/sonic v1.9.1 h1:6iJ6NqdoxCDr6mbY8h18oSO+cShGSMRGCEo7F2h0x8s=
github.com/bytedance/sonic v1.9.1/go.mod h1:i736AoUSYgA8oJ0G7iZjNgnfC2LtQL9U6bZ0BpmB2mI=
github.com/docker/docker v20.10.0+incompatible h1:JcmoK6Wg4vNv7pdrxTUQZ2q0aE1cCRHNIvJmqSMKPmM=
github.com/docker/docker v20.10.0+incompatible/go.mod h1:eEKB0N0r5NX/I1kEveEz05bcu8tLC/8azJZsviup8Sk=
github.com/gin-gonic/gin v1.9.1 h1:4idEAncQnU5cB7BeOkPtxjfCSye0AAm1R0RVIqJ+Jmg=
github.com/gin-gonic/gin v1.9.1/go.mod h1:hPrL7YrpYKXt5YId3A/Tnip5kqbEAP+KLuI3SUcPTeU=
github.com/go-playground/validator/v10 v10.14.0 h1:vgvQWe3XCz3gIeFDm/HnTIbj6UGmg/+t63MyGU2n5js=
github.com/go-playground/validator/v10 v10.14.0/go.mod h1:9iXMNT7sEkjXb0I+enO7QXmzG6QCsPWY4zveKFVRSyU=
github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8 h1:0A+M6Uqn+Eje4kHMK80dtF3JCXC4ykBgQG4Fe06QRhQ=
golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
`;

test('go.sum reports one package per module, not one per hash line', () => {
  const pkgs = parse(fixture('go.sum', GO_SUM));
  assert.deepEqual(idsOf(pkgs), [
    'github.com/bytedance/sonic@v1.9.1',
    'github.com/docker/docker@v20.10.0+incompatible',
    'github.com/gin-gonic/gin@v1.9.1',
    'github.com/go-playground/validator/v10@v10.14.0',
    'golang.org/x/sys@v0.0.0-20220715151400-c0bba94af5f8',
  ], 'the /go.mod twin is a hash of the manifest, not a release. Reported as a package ' +
     'it asks OSV about version "v1.9.1/go.mod", which matches no range and answers clean');
});

test('a module present only as a /go.mod hash is not invented as a package', () => {
  // stretchr/objx appears in the graph for version resolution but is not in the
  // build, so go.sum has only its go.mod hash. Reporting it at version
  // "v0.1.0/go.mod" is a query slot spent on a string no advisory can match.
  const pkgs = parse(fixture('go.sum', GO_SUM));
  assert.ok(!pkgs.some(p => p.name.includes('objx')),
    'a go.mod-only module was reported, and at a version that does not exist');
  assert.ok(!pkgs.some(p => p.version.includes('/')),
    'a version still carries the /go.mod suffix');
});

test('+incompatible, pseudo-versions and /vN module paths survive verbatim', () => {
  // Measured, not assumed: github.com/docker/docker returns the same 35
  // advisories for v20.10.0+incompatible, 20.10.0+incompatible, v20.10.0 and
  // 20.10.0, so OSV normalises the Go form and the least transformation here is
  // also the safest. The +incompatible suffix appears inside OSV's own Go
  // advisory ranges (GO-2024-3005 opens at "20.10.0+incompatible"), so stripping
  // it would be editing a string the advisories themselves use.
  const pkgs = parse(fixture('go.sum', GO_SUM));
  const byName = Object.fromEntries(pkgs.map(p => [p.name, p.version]));
  assert.equal(byName['github.com/docker/docker'], 'v20.10.0+incompatible');
  assert.equal(byName['golang.org/x/sys'], 'v0.0.0-20220715151400-c0bba94af5f8');
  assert.equal(byName['github.com/go-playground/validator/v10'], 'v10.14.0',
    'the /v10 major-version suffix is part of the module path OSV indexes; dropping it ' +
    'asks about a different module');
});

test('a go.sum line that is not "module version hash" throws', () => {
  const path = fixture('go.sum', 'github.com/gin-gonic/gin v1.9.1\n');
  assert.throws(() => parseManifest(path), /go\.sum: line 1/,
    'a truncated go.sum line was skipped. Skipping means the module is never queried, ' +
    'which is indistinguishable from the module being clean');
});

test('a repeated module@version is queried once', () => {
  const pkgs = parse(fixture('go.sum', GO_SUM + GO_SUM));
  assert.equal(pkgs.length, 5, 'duplicate module lines became duplicate OSV queries');
});

// ---------------------------------------------------------------------------
// Rust
// ---------------------------------------------------------------------------
//
// Cargo writes the local crate as a [[package]] with no `source`, and parks
// unused [patch] entries in [[patch.unused]] blocks that carry name and version
// exactly like a real package does.
const CARGO_LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my-service"
version = "0.1.0"
dependencies = [
 "libc",
 "time",
]

[[package]]
name = "libc"
version = "0.2.147"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b4668fb0ea861c1df094127ac5f1da3409a82116a4ba74fca2e58ef927159bb3"

[[package]]
name = "time"
version = "0.2.22"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "55b7151c9065e80917fbf285d9a5d1432f60db41d170ccafc749a136dcd0aeda"
dependencies = [
 "libc",
]

[[patch.unused]]
name = "winapi"
version = "0.4.0"

[metadata]
"checksum aho-corasick 0.7.18 (registry+https://github.com/rust-lang/crates.io-index)" = "1e37cfd5e7657ada45f742d6e99ca5788580b5c529dc78faf11ece6dc702656f"
`;

test('Cargo.lock reports registry crates and not the local crate', () => {
  const pkgs = parse(fixture('Cargo.lock', CARGO_LOCK));
  assert.deepEqual(idsOf(pkgs), ['libc@0.2.147', 'time@0.2.22'],
    'the workspace/root crate has no `source` because Cargo did not fetch it — it is ' +
    'published nowhere, so a query either matches nothing or matches an unrelated ' +
    'crate that happens to share the name');
});

test('a [[patch.unused]] block is neither a package nor a rename of the last one', () => {
  // It carries `name` and `version` at the same nesting a package does. A
  // reader that does not namespace keys by their table overwrites the previous
  // package's identity with winapi@0.4.0 — time 0.2.22, which has two
  // advisories against it (measured), silently becomes a crate that has none.
  const pkgs = parse(fixture('Cargo.lock', CARGO_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'winapi'), '[[patch.unused]] became a package');
  assert.ok(pkgs.some(p => p.name === 'time' && p.version === '0.2.22'),
    'the last real package lost its identity to the trailing [[patch.unused]] block');
});

test('a [[package]] with no version throws rather than being dropped', () => {
  const path = fixture('Cargo.lock', '[[package]]\nname = "libc"\nsource = "registry+x"\n');
  assert.throws(() => parseManifest(path), /Cargo\.lock: \[\[package\]\] at line 1 has no version/);
});

// ---------------------------------------------------------------------------
// Ruby
// ---------------------------------------------------------------------------
//
// The GEM specs block is indentation-sensitive: 4 spaces is an installed gem,
// 6 spaces is one of its dependency constraints. GIT and PATH sections repeat
// the same shape for gems that did not come from rubygems.org.
const GEMFILE_LOCK = `GIT
  remote: https://github.com/rails/rails.git
  revision: 6f0d1ca4b1e0bc94e0d8f6e1b4b0f1e7a0d0c0b0
  specs:
    railties (7.1.0.alpha)
      actionpack (= 7.1.0.alpha)

PATH
  remote: engines/billing
  specs:
    billing (0.1.0)
      rack

GEM
  remote: https://rubygems.org/
  specs:
    actionpack (7.0.4)
      actionview (= 7.0.4)
      activesupport (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
    nokogiri (1.13.5-x86_64-linux)
      racc (~> 1.4)
    racc (1.6.0)
    rack (2.2.4)
    rails (7.1.0.beta1)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  nokogiri
  railties!

CHECKSUMS
  rack (2.2.4) sha256=d1f0e3e8b7ee0e0f0c0a0e0b0d0c0a0e0b0d0c0a0e0b0d0c0a0e0b0d0c0a0e0b

BUNDLED WITH
   2.4.10
`;

test('only the 4-space GEM entries are installed gems', () => {
  const pkgs = parse(fixture('Gemfile.lock', GEMFILE_LOCK));
  assert.deepEqual(idsOf(pkgs), [
    'actionpack@7.0.4', 'nokogiri@1.13.5', 'racc@1.6.0', 'rack@2.2.4', 'rails@7.1.0.beta1',
  ], 'the specs block was read without regard to indentation');
});

test('a 6-space dependency constraint is not a gem at that version', () => {
  // `      rack (~> 2.0, >= 2.2.0)` is what actionpack ASKS FOR, not what is
  // installed. Read as a gem it queries rack at version "~> 2.0, >= 2.2.0",
  // which matches nothing — and it displaces the real rack 2.2.4 in any
  // dedupe keyed on name.
  const pkgs = parse(fixture('Gemfile.lock', GEMFILE_LOCK));
  assert.ok(!pkgs.some(p => /[~>=,]/.test(p.version)),
    'a dependency constraint was recorded as an installed version');
  assert.ok(!pkgs.some(p => p.name === 'actionview'),
    'actionview appears only as a constraint under actionpack and is not installed here');
});

test('GIT and PATH sections are not rubygems.org packages', () => {
  const pkgs = parse(fixture('Gemfile.lock', GEMFILE_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'railties'),
    'a gem resolved from a git checkout was queried against RubyGems, where its version ' +
    'need not correspond to any published release');
  assert.ok(!pkgs.some(p => p.name === 'billing'),
    'a PATH gem is local to the app and is published nowhere');
});

test('the platform suffix is stripped and the dotted prerelease is not', () => {
  // Measured against the live OSV API, and the reason this line exists:
  //   activerecord 7.0.0              -> 4 advisories
  //   activerecord 7.0.0-x86_64-linux -> 1 advisory
  // The three that vanish are the ones whose range opens at introduced 7.0.0 —
  // Ruby reads the hyphen as a prerelease separator, so the suffixed string
  // sorts BELOW the plain version and falls outside the range. Three silent
  // false cleans from one platform suffix. Ruby's own prereleases use dots
  // (7.1.0.beta1), so cutting at the first hyphen only ever removes a platform.
  const byName = Object.fromEntries(parse(fixture('Gemfile.lock', GEMFILE_LOCK))
    .map(p => [p.name, p.version]));
  assert.equal(byName.nokogiri, '1.13.5',
    'the platform suffix was left on the version, which moves it below every ' +
    '"introduced" boundary and hides the advisories that open there');
  assert.equal(byName.rails, '7.1.0.beta1',
    'a dotted Ruby prerelease was truncated — that is a different version');
});

test('a 4-space line inside GEM specs that is not "name (version)" throws', () => {
  const path = fixture('Gemfile.lock', 'GEM\n  remote: https://rubygems.org/\n  specs:\n    rack 2.2.4\n');
  assert.throws(() => parseManifest(path), /Gemfile\.lock: line 4/,
    'an unparseable spec line was skipped, so the gem is never queried and the app ' +
    'reads as clean');
});

// ---------------------------------------------------------------------------
// Python — poetry
// ---------------------------------------------------------------------------
//
// Poetry 1.5 format: each [[package]] is followed by nested tables —
// [package.dependencies], [package.extras], [package.source] — whose lines
// contain `=` and sit at the same indentation as the block's own keys.
const POETRY_LOCK = `# This file is automatically @generated by Poetry 1.5.1 and should not be changed by hand.

[[package]]
name = "certifi"
version = "2023.7.22"
description = "Python package for providing Mozilla's CA Bundle."
optional = false
python-versions = ">=3.6"
files = [
    {file = "certifi-2023.7.22-py3-none-any.whl", hash = "sha256:92d6037539857d8206b8f6ae472e8b77db8dd2497"},
    {file = "certifi-2023.7.22.tar.gz", hash = "sha256:539cc1d13202e33ca466e88b2807e29f4c13049d"},
]

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = []

[package.dependencies]
certifi = ">=2017.4.17"
urllib3 = ">=1.21.1,<3"

[package.extras]
socks = ["PySocks (>=1.5.6,!=1.5.7)"]

[[package]]
name = "billing"
version = "0.1.0"
description = "The app's own engine"
optional = false
python-versions = "^3.11"
files = []
develop = true

[package.source]
type = "directory"
url = "engines/billing"

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "8b0c8a0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e"
`;

test('poetry.lock reports the packages and not their constraints', () => {
  const pkgs = parse(fixture('poetry.lock', POETRY_LOCK));
  assert.deepEqual(idsOf(pkgs), ['certifi@2023.7.22', 'requests@2.31.0'],
    '[package.dependencies] lists what a package ASKS FOR — urllib3 ">=1.21.1,<3" is a ' +
    'range, not an installed version, and there is no way to query it');
  assert.ok(!pkgs.some(p => p.name === 'urllib3'),
    'a constraint under [package.dependencies] became a package');
});

test('a directory source is the app itself, not a PyPI package', () => {
  // The exclusion depends on reading `type` under [package.source] rather than
  // as a block-level key. A reader that flattens nested tables never sees the
  // namespaced key, keeps the block, and queries PyPI for "billing" 0.1.0 —
  // where an unrelated project of that name may well answer.
  const pkgs = parse(fixture('poetry.lock', POETRY_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'billing'),
    'a path dependency was queried against PyPI');
});

test('a poetry package with no version throws', () => {
  const path = fixture('poetry.lock', '[[package]]\nname = "certifi"\noptional = false\n');
  assert.throws(() => parseManifest(path), /poetry\.lock: \[\[package\]\] at line 1 has no version/);
});

// ---------------------------------------------------------------------------
// Python — pipenv
// ---------------------------------------------------------------------------

const PIPFILE_LOCK = JSON.stringify({
  _meta: {
    hash: { sha256: 'aa0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e' },
    'pipfile-spec': 6,
    requires: { python_version: '3.11' },
    sources: [{ name: 'pypi', url: 'https://pypi.org/simple', verify_ssl: true }],
  },
  default: {
    certifi: { hashes: ['sha256:92d60375'], markers: "python_version >= '3.6'", version: '==2023.7.22' },
    requests: { hashes: ['sha256:942c5a75'], index: 'pypi', version: '==2.31.0' },
    'internal-lib': { git: 'https://github.com/example/internal-lib.git', ref: '6f0d1ca4b1e0' },
  },
  develop: {
    pytest: { hashes: ['sha256:b4bf8c45'], version: '==7.4.0' },
  },
}, null, 2);

test('Pipfile.lock covers default and develop, with the == pin removed', () => {
  const pkgs = parse(fixture('Pipfile.lock', PIPFILE_LOCK));
  assert.deepEqual(idsOf(pkgs), ['certifi@2023.7.22', 'pytest@7.4.0', 'requests@2.31.0'],
    'develop dependencies run in CI and ship in dev images; leaving them out is the ' +
    'under-report this feature exists to prevent');
  assert.ok(!pkgs.some(p => p.version.startsWith('=')),
    'the "==" pin was passed through as part of the version, which matches no range');
});

test('_meta is not mistaken for a package section', () => {
  const pkgs = parse(fixture('Pipfile.lock', PIPFILE_LOCK));
  assert.ok(!pkgs.some(p => ['hash', 'sources', 'requires', 'pipfile-spec'].includes(p.name)));
});

test('a git requirement pins a ref, not a release, and is left out', () => {
  const pkgs = parse(fixture('Pipfile.lock', PIPFILE_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'internal-lib'),
    'a VCS requirement has no version; inventing one is the requirements.txt mistake');
});

test('an unpinned Pipfile.lock entry is an error, not a guess', () => {
  // pipenv always writes "==<version>". Anything else means the file is not
  // what it claims to be, and a range has no single installed version — an
  // 'error' is visible and gets fixed, a quietly dropped package is not.
  const path = fixture('Pipfile.lock', JSON.stringify({ default: { django: { version: '>=4.2' } } }));
  assert.throws(() => parseManifest(path), /"django" in default is not pinned/,
    'a range was accepted as a version, which answers confidently about a release ' +
    'that may not be installed');
});

test('a JSON file with no default or develop section is not a Pipfile.lock', () => {
  const path = fixture('Pipfile.lock', JSON.stringify({ _meta: { 'pipfile-spec': 6 } }));
  assert.throws(() => parseManifest(path), /no "default" or "develop" section/,
    'an unrecognised JSON file parsed to zero packages — a clean scan for a file ' +
    'nothing understood');
});

// ---------------------------------------------------------------------------
// PHP — composer
// ---------------------------------------------------------------------------
//
// Shaped on BookStack's own composer.lock, which is the case this row exists
// for: 151 packages across `packages` and `packages-dev`, 64 of them carrying a
// leading v on the version. `platform` and `platform-dev` sit alongside them
// holding php and ext-* entries, which are not Packagist packages at all.
const COMPOSER_LOCK = JSON.stringify({
  _readme: ['This file locks the dependencies of your project to a known state'],
  'content-hash': '3a0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e',
  packages: [
    {
      name: 'guzzlehttp/guzzle',
      version: '7.5.0',
      source: { type: 'git', url: 'https://github.com/guzzle/guzzle.git', reference: 'b50a2a1251152e43f6a37f0fa053e730a67d25ba' },
      dist: { type: 'zip', url: 'https://api.github.com/repos/guzzle/guzzle/zipball/b50a2a12', reference: 'b50a2a12', shasum: '' },
      require: { php: '^7.2.5 || ^8.0' },
      type: 'library',
    },
    {
      name: 'laravel/framework',
      version: 'v9.52.4',
      source: { type: 'git', url: 'https://github.com/laravel/framework.git', reference: 'f2b9c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0' },
      dist: { type: 'zip', url: 'https://api.github.com/repos/laravel/framework/zipball/f2b9c0d0', reference: 'f2b9c0d0', shasum: '' },
      type: 'library',
    },
    {
      name: 'symfony/polyfill-intl-idn',
      version: 'v1.27.0',
      source: { type: 'git', url: 'https://github.com/symfony/polyfill-intl-idn.git', reference: '639084e360537a19f9ee352433b84ce831f3d2da' },
      type: 'library',
    },
    {
      name: 'acme/nightly-widget',
      version: 'dev-main',
      source: { type: 'git', url: 'https://github.com/acme/nightly-widget.git', reference: '0f0e0d0c0b0a09080706050403020100f0e0d0c0' },
      type: 'library',
    },
    {
      name: 'acme/branch-aliased',
      version: '3.4.x-dev',
      source: { type: 'git', url: 'https://github.com/acme/branch-aliased.git', reference: '1a2b3c4d5e6f70819283a4b5c6d7e8f901234567' },
      type: 'library',
    },
  ],
  'packages-dev': [
    {
      name: 'phpunit/phpunit',
      version: '9.6.3',
      source: { type: 'git', url: 'https://github.com/sebastianbergmann/phpunit.git', reference: 'e7bdf4c6ae0d4ba9c1e0d0b0a0908070605040302' },
      type: 'library',
    },
  ],
  aliases: [],
  'minimum-stability': 'stable',
  platform: { php: '^8.0.2', 'ext-json': '*', 'ext-mbstring': '*' },
  'platform-dev': [],
  'plugin-api-version': '2.3.0',
}, null, 2);

test('composer.lock covers packages and packages-dev', () => {
  const pkgs = parse(fixture('composer.lock', COMPOSER_LOCK));
  assert.deepEqual(idsOf(pkgs), [
    'guzzlehttp/guzzle@7.5.0',
    'laravel/framework@9.52.4',
    'phpunit/phpunit@9.6.3',
    'symfony/polyfill-intl-idn@1.27.0',
  ], 'require-dev packages run in CI and ship in dev images; leaving them out is the ' +
     'under-report this feature exists to prevent');
});

test('the leading v on a Composer tag is not part of the version', () => {
  // Composer writes the git TAG. OSV does not: its Packagist advisories spell
  // every boundary and every enumerated version bare — guzzlehttp/guzzle's
  // version list runs "6.5.7", "6.5.8", and GHSA-cwxw-98qj-8qjx opens at fixed
  // "7.12.1" — because Packagist normalises the tag prefix away itself.
  //
  // Measured before deciding, and reported honestly: the OSV /v1/query endpoint
  // normalises the v too, so "v9.52.4" and "9.52.4" return the same 4
  // advisories for laravel/framework today, as do all eleven v-prefixed
  // packages in BookStack v23.02 that have findings. The strip is a
  // data-hygiene choice, NOT a fix for a measured miss: it makes the recorded
  // version match the spelling OSV's own data and its `fixed` field use, so a
  // digest never reports "v6.0.19 — fixed in 6.0.20". The mirror of the Go rule
  // above, which KEEPS +incompatible precisely because that suffix does appear
  // inside OSV's Go ranges.
  const byName = Object.fromEntries(parse(fixture('composer.lock', COMPOSER_LOCK))
    .map(p => [p.name, p.version]));
  assert.equal(byName['laravel/framework'], '9.52.4');
  assert.equal(byName['symfony/polyfill-intl-idn'], '1.27.0');
  assert.equal(byName['guzzlehttp/guzzle'], '7.5.0', 'a version with no v prefix was altered');
});

test('a Composer branch pin is not a release and is left out', () => {
  // dev-main and 3.4.x-dev mean "whatever that branch points at today". OSV
  // returns nothing for either string, and picking the branch alias instead
  // would be the requirements.txt mistake — a confident answer about a version
  // that may not be installed.
  const pkgs = parse(fixture('composer.lock', COMPOSER_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'acme/nightly-widget'), 'dev-main was queried as a version');
  assert.ok(!pkgs.some(p => p.name === 'acme/branch-aliased'), '3.4.x-dev was queried as a version');
  assert.ok(!pkgs.some(p => /dev/.test(p.version)), 'a branch pin reached the query set');
});

test('platform requirements are not Packagist packages', () => {
  // `platform` holds php and ext-* — the interpreter and its extensions.
  // Querying Packagist for "php" at "^8.0.2" spends a slot on a constraint, and
  // "ext-json" is not a package anyone publishes.
  const pkgs = parse(fixture('composer.lock', COMPOSER_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'php' || p.name.startsWith('ext-')),
    'a platform requirement was read as a Packagist package');
});

test('a composer.lock entry with no version throws rather than being dropped', () => {
  const path = fixture('composer.lock',
    JSON.stringify({ packages: [{ name: 'guzzlehttp/guzzle', type: 'library' }] }));
  assert.throws(() => parseManifest(path), /"guzzlehttp\/guzzle" in packages has no version/);
});

test('a JSON file with no packages array is not a composer.lock', () => {
  const path = fixture('composer.lock', JSON.stringify({ 'content-hash': 'abc', platform: {} }));
  assert.throws(() => parseManifest(path), /no "packages" or "packages-dev" array/,
    'an unrecognised JSON file parsed to zero packages — a clean scan for a file ' +
    'nothing understood');
});

// ---------------------------------------------------------------------------
// yarn — classic (v1)
// ---------------------------------------------------------------------------
//
// Every line below is a shape lifted from real v1 lockfiles. The ansi-html
// entry is verbatim from one: a `resolutions` override that keeps the old name
// in the key and swaps a different package in behind it. The Artifactory URL is
// the mirror layout, where the registry serves the same /-/ path under a prefix.
const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.12.13", "@babel/code-frame@^7.18.6":
  version "7.18.6"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.18.6.tgz#3b25d38c89600baa2dcc219edfa88a74eb2c427a"
  integrity sha512-TDCmlK5eOvH+eH7cdAFlNXeVJqWIQ7gW9tY1GJIpUtFb6CmjVyq2VM3u71bOyR8CRihcCgMUYoDNyLXao3+70Q==
  dependencies:
    "@babel/highlight" "^7.18.6"

"@company/ui@^1.0.0":
  version "1.2.0"
  resolved "https://artifactory.example.com/api/npm/npm-remote/@company/ui/-/ui-1.2.0.tgz#a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0"

ansi-html@0.0.7, ansi-html@^0.0.7, "ansi-html@https://registry.yarnpkg.com/ansi-html-community/-/ansi-html-community-0.0.8.tgz#69fbc4d6ccbe383f9736934ae34c3f8290f1bf41":
  version "0.0.8"
  resolved "https://registry.yarnpkg.com/ansi-html-community/-/ansi-html-community-0.0.8.tgz#69fbc4d6ccbe383f9736934ae34c3f8290f1bf41"

lodash@^3.10.1:
  version "3.10.1"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz#5bf45e8e49ba4189e17d482789dfd15bd140b7b6"
  integrity sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y=

"mylodash@npm:lodash@4.17.15":
  version "4.17.15"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz#b447f6670a0455bbfeedd11392eff330ea097548"

"xlsx@https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz":
  version "0.20.2"
  resolved "https://cdn.sheetjs.com/xlsx-0.20.2/xlsx-0.20.2.tgz#0f64eeed3f1a46e6479d3e78c1a1b3f0ff6a4a4e"

"local-engine@file:../engines/billing":
  version "0.1.0"

"myminimist@npm:minimist@1.2.6":
  version "1.2.6"
`;

test('a yarn v1 lockfile yields the published packages under their real names', () => {
  const pkgs = parse(fixture('yarn.lock', YARN_V1));
  assert.deepEqual(idsOf(pkgs), [
    '@babel/code-frame@7.18.6',
    '@company/ui@1.2.0',
    'ansi-html-community@0.0.8',
    'lodash@3.10.1',
    'lodash@4.17.15',
    'minimist@1.2.6',
  ], 'the query set is not the installed registry set');
});

test('a scoped yarn v1 package round-trips with its scope intact', () => {
  // The descriptor opens with an @ that is NOT the name/range separator. A
  // reader that splits on the first @ at position 0 emits a package called ""
  // at version "babel/code-frame@^7.0.0"; one that splits on the LAST @ is
  // right here and wrong for a git range, which ends in one.
  const pkgs = parse(fixture('yarn.lock', YARN_V1));
  assert.ok(pkgs.some(p => p.name === '@babel/code-frame' && p.version === '7.18.6'),
    'the scope was lost or the range was read as the version');
  assert.ok(pkgs.some(p => p.name === '@company/ui' && p.version === '1.2.0'),
    'a scoped package behind a registry mirror lost its scope — the name is taken from ' +
    'the segments before /-/, not the ones after the host, or the mirror yields "api"');
});

test('several yarn v1 descriptors sharing one entry are one package', () => {
  // "@babel/code-frame@^7.0.0", "^7.12.13" and "^7.18.6" all resolved to
  // 7.18.6. Three query slots for one answer, and three identical rows in a
  // report a human reads.
  const pkgs = parse(fixture('yarn.lock', YARN_V1));
  assert.equal(pkgs.filter(p => p.name === '@babel/code-frame').length, 1);
});

test('a yarn v1 alias is queried under the package name, not the alias', () => {
  const pkgs = parse(fixture('yarn.lock', YARN_V1));
  assert.ok(pkgs.some(p => p.name === 'lodash' && p.version === '4.17.15'),
    'the aliased lodash@4.17.15 was not queried under the name lodash');
  assert.ok(!pkgs.some(p => p.name === 'mylodash'),
    'the alias "mylodash" was sent to OSV — no registry has it, so the answer is a ' +
    'guaranteed false clean');
});

test('an alias with no resolved line still resolves through the descriptor', () => {
  // `myminimist` carries no `resolved`, so the URL authority has nothing to say
  // and the descriptor rules decide. This is the only path on which the
  // name/range split matters: read with the LAST @ the descriptor
  // "myminimist@npm:minimist@1.2.6" yields a package called
  // "myminimist@npm:minimist", which no registry has. Read with the first @
  // after the scope it yields the minimist that is installed.
  const pkgs = parse(fixture('yarn.lock', YARN_V1));
  assert.ok(pkgs.some(p => p.name === 'minimist' && p.version === '1.2.6'),
    'the fallback path lost the aliased package');
  assert.ok(!pkgs.some(p => p.name.includes('npm:')),
    'an alias protocol leaked into a package name');
});

test('a yarn v1 resolutions override is named for what is installed', () => {
  // Verbatim from a real lockfile. The entry is keyed ansi-html and installs
  // ansi-html-community 0.0.8. Read from the key it reports ansi-html 0.0.8 —
  // a version ansi-html has never published, so OSV answers clean for a
  // package that is genuinely on disk. This is why `resolved` is the authority
  // and the descriptors are only the fallback: across 11 real v1 lockfiles and
  // 10221 entries, `resolved` was present on every one and disagreed with the
  // descriptor exactly here.
  const pkgs = parse(fixture('yarn.lock', YARN_V1));
  assert.ok(pkgs.some(p => p.name === 'ansi-html-community' && p.version === '0.0.8'),
    'the override was read from the entry key instead of the resolved tarball');
  assert.ok(!pkgs.some(p => p.name === 'ansi-html'),
    'ansi-html 0.0.8 was queried — that release does not exist, so it answers clean');
});

test('a yarn v1 tarball or file dependency has no registry release to ask about', () => {
  const pkgs = parse(fixture('yarn.lock', YARN_V1));
  assert.ok(!pkgs.some(p => p.name === 'xlsx'),
    'a CDN tarball was queried against the npm registry, where its version need not ' +
    'correspond to any published release');
  assert.ok(!pkgs.some(p => p.name === 'local-engine'),
    'a file: dependency is local to the app and is published nowhere');
});

test('a yarn v1 entry with no version throws rather than being dropped', () => {
  const path = fixture('yarn.lock',
    '# yarn lockfile v1\n\nlodash@^3.10.1:\n  resolved "https://registry.yarnpkg.com/lodash/-/lodash-3.10.1.tgz#5bf4"\n');
  assert.throws(() => parseManifest(path), /yarn\.lock: the entry at line 3 has no version/,
    'a versionless entry was skipped, so the package is never queried, which is ' +
    'indistinguishable from the package being clean');
});

// ---------------------------------------------------------------------------
// yarn — berry (v2+)
// ---------------------------------------------------------------------------
//
// Every entry below is a real shape from yarn's own lockfile: an alias whose
// target is scoped (react-loadable -> @docusaurus/react-loadable), a patched
// registry package, a workspace member, and a git resolution. Berry is YAML,
// classic is not, and the two spell every version differently.
const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 10
  cacheKey: 10

"@algolia/autocomplete-core@npm:1.17.9":
  version: 1.17.9
  resolution: "@algolia/autocomplete-core@npm:1.17.9"
  dependencies:
    "@algolia/autocomplete-shared": "npm:1.17.9"
  checksum: 10/cf4f0f1d9e0ca4e7f1ea25291b270e47315385cbda4a01bbc0c56c3659d21f23
  languageName: node
  linkType: hard

"esbuild@npm:esbuild-wasm@^0.23.0":
  version: 0.23.0
  resolution: "esbuild-wasm@npm:0.23.0"
  bin:
    esbuild: bin/esbuild
  checksum: 10/a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0
  languageName: node
  linkType: hard

"react-loadable@npm:@docusaurus/react-loadable@6.0.0":
  version: 6.0.0
  resolution: "@docusaurus/react-loadable@npm:6.0.0"
  dependencies:
    "@types/react": "npm:*"
  peerDependencies:
    react: "*"
  checksum: 10/b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0d0e0f0a0b0c0
  languageName: node
  linkType: hard

"fsevents@patch:fsevents@npm%3A^2.3.2#optional!builtin<compat/fsevents>, fsevents@patch:fsevents@npm%3A~2.3.2#optional!builtin<compat/fsevents>":
  version: 2.3.2
  resolution: "fsevents@patch:fsevents@npm%3A2.3.2#optional!builtin<compat/fsevents>::version=2.3.2&hash=df0bf1"
  dependencies:
    node-gyp: "npm:latest"
  conditions: os=darwin
  languageName: node
  linkType: hard

"pem@https://github.com/dexus/pem.git#commit=71dae3346801dafb5a8bcebcd4c7267fd182666f":
  version: 1.14.8
  resolution: "pem@https://github.com/dexus/pem.git#commit=71dae3346801dafb5a8bcebcd4c7267fd182666f"
  languageName: node
  linkType: hard

"@fixture/builder@workspace:packages/fixture-builder":
  version: 0.0.0-use.local
  resolution: "@fixture/builder@workspace:packages/fixture-builder"
  dependencies:
    "@types/semver": "npm:^7.1.0"
  languageName: unknown
  linkType: soft
`;

test('a yarn berry lockfile is read from resolution, not from the entry key', () => {
  const pkgs = parse(fixture('yarn.lock', YARN_BERRY));
  assert.deepEqual(idsOf(pkgs), [
    '@algolia/autocomplete-core@1.17.9',
    '@docusaurus/react-loadable@6.0.0',
    'esbuild-wasm@0.23.0',
    'fsevents@2.3.2',
  ], 'the query set is not the installed registry set');
});

test('a berry alias resolves to the real package, scope and all', () => {
  // Both lines are real: docusaurus ships an UNSCOPED alias of a SCOPED
  // package, and esbuild-wasm arrives keyed as esbuild. Read from the entry key
  // both are names npm has never published at those versions, so OSV answers
  // clean twice.
  const pkgs = parse(fixture('yarn.lock', YARN_BERRY));
  assert.ok(pkgs.some(p => p.name === '@docusaurus/react-loadable' && p.version === '6.0.0'),
    'an unscoped alias of a scoped package kept the alias name');
  assert.ok(!pkgs.some(p => p.name === 'react-loadable'), 'the alias reached the query set');
  assert.ok(!pkgs.some(p => p.name === 'esbuild'), 'esbuild-wasm was queried as esbuild');
});

test('a patched berry package keeps its upstream identity and advisories', () => {
  // patch: is a local diff over a registry release. The ident and the version
  // are both the upstream ones, so the advisories still apply — dropping the
  // entry would hide a finding on a package that is genuinely installed. Its
  // resolution embeds a whole second descriptor after the protocol
  // (fsevents@patch:fsevents@npm%3A2.3.2#...), so a reader that splits on the
  // LAST @ names it "fsevents@patch:fsevents".
  const pkgs = parse(fixture('yarn.lock', YARN_BERRY));
  assert.ok(pkgs.some(p => p.name === 'fsevents' && p.version === '2.3.2'),
    'a patched registry package was dropped or misnamed');
  assert.ok(!pkgs.some(p => p.name.includes('patch')), 'a patch protocol leaked into a name');
});

test('berry workspace members and git resolutions are not registry packages', () => {
  const pkgs = parse(fixture('yarn.lock', YARN_BERRY));
  assert.ok(!pkgs.some(p => p.name === '@fixture/builder'),
    'a workspace member is published nowhere, and its 0.0.0-use.local is not a release');
  assert.ok(!pkgs.some(p => p.version.includes('use.local')));
  assert.ok(!pkgs.some(p => p.name === 'pem'),
    'a git resolution was queried against npm, where its version need not correspond ' +
    'to any published release');
});

test('__metadata is the lockfile header, not a package', () => {
  // It carries `version: 10` — the LOCKFILE version — at exactly the
  // indentation a package's own version sits at.
  const pkgs = parse(fixture('yarn.lock', YARN_BERRY));
  assert.ok(!pkgs.some(p => p.name === '__metadata'), '__metadata was reported as a package');
  assert.ok(!pkgs.some(p => p.version === '10'), 'the lockfile version was read as a release');
});

test('a berry entry with no resolution throws rather than being dropped', () => {
  const path = fixture('yarn.lock',
    '__metadata:\n  version: 10\n\n"lodash@npm:^4.17.21":\n  version: 4.17.21\n  linkType: hard\n');
  assert.throws(() => parseManifest(path), /yarn\.lock: the entry at line 4 has no "resolution:"/,
    'an entry with no resolution was skipped, and resolution is the only field that ' +
    'says what the package actually IS');
});

test('a yarn.lock in neither format is refused, loudly', () => {
  // Reading berry with classic rules finds no `version "x"` lines at all and
  // returns nothing — a clean scan for a file nothing understood. The format is
  // identified from its own marker instead, and an unmarked file is an error.
  const path = fixture('yarn.lock', 'lodash@^4.17.21:\n  version "4.17.21"\n');
  assert.throws(() => parseManifest(path),
    /no "# yarn lockfile v1" header and no "__metadata:" block/);
});

test('an empty yarn v1 lockfile is legal and is not an error', () => {
  // A real one on this machine: a project whose package.json has no
  // dependencies still gets the two header comments and nothing else. Zero
  // packages here means zero dependencies, which is a true answer.
  const pkgs = parse(fixture('yarn.lock',
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n'));
  assert.deepEqual(pkgs, []);
});

// ---------------------------------------------------------------------------
// pnpm
// ---------------------------------------------------------------------------
//
// lockfileVersion 9.0, the format pnpm 9 and pnpm 10 both write. Shaped on
// three real 9.0 lockfiles (745, 1701 and 1719 package keys). Two traps are
// load-bearing and both are in here: `importers:` and `snapshots:` repeat
// package-shaped keys either side of `packages:`, and snapshots keys carry the
// peer-dependency suffix that packages keys do not. The node@runtime:26.8.1
// entry is verbatim from pnpm's own lockfile.
const PNPM_LOCK_9 = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      react:
        specifier: ^18.3.1
        version: 18.3.1
      react-dom:
        specifier: ^18.3.1
        version: 18.3.1(react@18.3.1)
      '@fixture/contracts':
        specifier: workspace:*
        version: link:../packages/contracts

packages:

  '@babel/code-frame@7.29.7':
    resolution: {integrity: sha512-Aup7aUOfpbAUg2ROOJN6Iw5f9DMBlzu0mIkm/malLQFN/YQgO48wCj0Kxa3sEHJvPVFg7siR+qRInwXd2qhQKw==}
    engines: {node: '>=6.9.0'}

  esbuild@0.21.5:
    resolution: {integrity: sha512-mg3OPMV4hXywwpoDxu3Qda5xCKQi+vCTZq8S9J/EpkhB2HzKXq4SNFZE3+NK93JYxc8VMSep+lOUSC/RVKaBqw==}
    engines: {node: '>=12'}
    hasBin: true

  node@runtime:26.8.1:
    resolution: {integrity: sha512-0000000000000000000000000000000000000000000000000000000000000000000000000000000000000A==}

  react-dom@18.3.1:
    resolution: {integrity: sha512-5m4nQKp+rZRb09LNH59GM4BxTh9251/ylbKIbpe7TpGxfJ+9kv6BLkLBXIjjspbgbnIBNqlI23tRnTWT0snUIw==}
    peerDependencies:
      react: ^18.3.1

  react@18.3.1:
    resolution: {integrity: sha512-wS+hAgJShR0KhEvPJArfuPVN1+Hz1t0Y6n5jLrGQbkb4urgPE/0Rve+1kMB1v/oWgHgm4WIcV+i7F2pTVj+2iQ==}
    engines: {node: '>=0.10.0'}

snapshots:

  '@babel/code-frame@7.29.7': {}

  esbuild@0.21.5: {}

  react-dom@18.3.1(react@18.3.1):
    dependencies:
      react: 18.3.1

  react@18.3.1: {}
`;

test('a pnpm 9 lockfile reports the packages section and nothing else', () => {
  const pkgs = parse(fixture('pnpm-lock.yaml', PNPM_LOCK_9));
  assert.deepEqual(idsOf(pkgs), [
    '@babel/code-frame@7.29.7',
    'esbuild@0.21.5',
    'react-dom@18.3.1',
    'react@18.3.1',
  ], 'the query set is not the resolved registry set');
});

test('a scoped pnpm package round-trips with its scope intact', () => {
  // The key is name@version, so the separator is the LAST @ — the opposite of
  // yarn, where the range can contain one. A reader that splits on the first @
  // emits a package called "" at version "babel/code-frame@7.29.7".
  const pkgs = parse(fixture('pnpm-lock.yaml', PNPM_LOCK_9));
  assert.ok(pkgs.some(p => p.name === '@babel/code-frame' && p.version === '7.29.7'),
    'the scope was lost or the version absorbed part of the name');
});

test('importers and snapshots are not the packages section', () => {
  // Both sit at the same indentation and both hold package-shaped keys.
  // `importers:` lists the app's OWN workspaces and their specifiers, and
  // `snapshots:` repeats every package with a peer-dependency suffix —
  // react-dom@18.3.1(react@18.3.1) read as a package is a version string that
  // matches no range, and a duplicate query slot for one already asked.
  const pkgs = parse(fixture('pnpm-lock.yaml', PNPM_LOCK_9));
  assert.equal(pkgs.filter(p => p.name === 'react-dom').length, 1,
    'the snapshots entry was counted as a second react-dom');
  assert.ok(!pkgs.some(p => /[()]/.test(p.version)),
    'a peer-dependency suffix was read as part of the version');
  assert.ok(!pkgs.some(p => p.name === '.' || p.name.includes('specifier')),
    'the importers section was read as packages');
});

test('a pnpm key that is not name@<version> has no registry release behind it', () => {
  // node@runtime:26.8.1 is verbatim from pnpm's own lockfile — the runtime:
  // protocol, one of 1701 keys and the only non-registry one. Tarball and git
  // dependencies key the same way, with a URL where the version goes. A version
  // that does not begin with a digit is not a version.
  const pkgs = parse(fixture('pnpm-lock.yaml', PNPM_LOCK_9));
  assert.ok(!pkgs.some(p => p.name === 'node'), 'the node runtime was queried as an npm package');
  assert.ok(!pkgs.some(p => p.version.includes(':')), 'a protocol reached a version string');
});

test('a peer-dependency suffix is cut off, wherever it turns up', () => {
  // Measured at 0 of 4165 keys across three real 9.0 lockfiles: `packages:`
  // holds the deduplicated set and the peer variants live in `snapshots:`. But
  // the suffixed spelling IS real, it is in the same file a few hundred lines
  // down, and it is what a section-detection slip would feed in here — so the
  // cut is pinned by a test rather than left as untested defence. Uncut, the
  // last @ lands inside the parens: react-dom becomes a package named
  // "react-dom@18.3.1(react" at version "18.3.1)".
  const pkgs = parse(fixture('pnpm-lock.yaml',
    "lockfileVersion: '9.0'\n\npackages:\n\n  react-dom@18.3.1(react@18.3.1):\n    resolution: {integrity: sha512-abc}\n"));
  assert.deepEqual(idsOf(pkgs), ['react-dom@18.3.1']);
});

test('a pnpm lockfile older than 9.x is refused by version, not read wrongly', () => {
  // Real lockfileVersion 5.4 content. 5.x keys packages as /name/version, so
  // read as 9.x it yields the package "/typescript/4" at version "7.4" — a name
  // no registry has, and therefore a clean answer for every dependency in the
  // app. An error names the file and says how to fix it; a silent empty list
  // does not.
  const path = fixture('pnpm-lock.yaml',
    `lockfileVersion: 5.4\n\nspecifiers:\n  typescript: ^4.6.2\n\ndevDependencies:\n  typescript: 4.7.4\n\npackages:\n\n  /typescript/4.7.4:\n    resolution: {integrity: sha512-C0WQT0gezHuw6AdY1M2jxUO83Rjf0HP7Sk1DtXj6j1EwkQNZrHAg2XPWlq62oqEhYvONq5pkC2Y9oPljWToLmQ==}\n    engines: {node: '>=4.2.0'}\n    hasBin: true\n    dev: true\n`);
  assert.throws(() => parseManifest(path), /lockfileVersion "5\.4" is not read — only 9\.x is/,
    'a 5.x lockfile was parsed on a best-effort basis instead of being refused');
});

test('a pnpm 6.x lockfile is refused too', () => {
  const path = fixture('pnpm-lock.yaml',
    "lockfileVersion: '6.0'\n\npackages:\n\n  /typescript@4.7.4:\n    resolution: {integrity: sha512-abc}\n");
  assert.throws(() => parseManifest(path), /lockfileVersion "6\.0" is not read/);
});

test('a YAML file with no lockfileVersion is not a pnpm-lock.yaml', () => {
  const path = fixture('pnpm-lock.yaml', 'packages:\n\n  lodash@4.17.21:\n    resolution: {}\n');
  assert.throws(() => parseManifest(path), /no lockfileVersion/,
    'an unrecognised YAML file parsed to a package list without ever establishing ' +
    'which key format it was in');
});

test('a pnpm lockfile with no packages section throws', () => {
  const path = fixture('pnpm-lock.yaml',
    "lockfileVersion: '9.0'\n\nimporters:\n\n  .:\n    dependencies:\n      react:\n        specifier: ^18.3.1\n        version: 18.3.1\n");
  assert.throws(() => parseManifest(path), /no "packages:" section/,
    'nothing was read, and nothing-read must not be recorded as nothing-vulnerable');
});

// ---------------------------------------------------------------------------
// the shape contract, across every parser
// ---------------------------------------------------------------------------

test('every package from every parser carries its table row ecosystem', () => {
  // The ecosystem travels WITH the package rather than being applied at query
  // time, which is what lets one scan mix ecosystems in a single OSV batch. A
  // parser that forgets it emits a package the asserter rejects.
  const cases = [
    ['package-lock.json', NPM_LOCK, 'npm'],
    ['yarn.lock', YARN_V1, 'npm'],
    ['yarn.lock', YARN_BERRY, 'npm'],
    ['pnpm-lock.yaml', PNPM_LOCK_9, 'npm'],
    ['composer.lock', COMPOSER_LOCK, 'Packagist'],
    ['go.sum', GO_SUM, 'Go'],
    ['Cargo.lock', CARGO_LOCK, 'crates.io'],
    ['Gemfile.lock', GEMFILE_LOCK, 'RubyGems'],
    ['poetry.lock', POETRY_LOCK, 'PyPI'],
    ['Pipfile.lock', PIPFILE_LOCK, 'PyPI'],
  ];
  for (const [file, contents, ecosystem] of cases) {
    const pkgs = parse(fixture(file, contents));
    assert.ok(pkgs.length > 0, `${file} parsed to nothing`);
    for (const p of pkgs) {
      assertPackage(p, file);
      assert.equal(p.ecosystem, ecosystem, `${file} emitted ecosystem ${p.ecosystem}`);
    }
  }
});
