import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';

import { MANIFESTS, parseManifest } from '../server/services/ecosystems.js';
import { assertPackage } from '../server/services/scanShapes.js';

// The manifest table (v2.53.0).
//
// Everything here is about the same failure: a package name or version derived
// wrongly is not a missing answer, it is a WRONG one. OSV replies "no
// vulnerabilities" for a package that does not exist, so a parser bug is
// recorded as a clean app and reads as safety. Each fixture below is a shape
// that produces exactly that if read naively, and the assertions name the false
// clean rather than the diff.
//
// Fixtures are written to disk and read through parseManifest — the production
// entry point — rather than handed to the parsers as strings, because the file
// read, the filename dispatch and the assertPackage sweep are all part of the
// contract.

const DIR = mkdtempSync(join(tmpdir(), 'crane-eco-'));

function fixture(name, contents) {
  const path = join(DIR, name);
  writeFileSync(path, contents);
  return path;
}

/** Every parser's output must be assertPackage-valid; check it at every call. */
function parse(path, entry) {
  const pkgs = parseManifest(path, entry);
  pkgs.forEach((p, i) => assertPackage(p, `${path}[${i}]`));
  return pkgs;
}

const idsOf = (pkgs) => pkgs.map(p => `${p.name}@${p.version}`).sort();

// ---------------------------------------------------------------------------
// the table
// ---------------------------------------------------------------------------

test('the table maps six manifests onto OSV ecosystem names', () => {
  assert.deepEqual(
    MANIFESTS.map(m => [m.file, m.ecosystem]),
    [
      ['package-lock.json', 'npm'],
      ['go.sum', 'Go'],
      ['Cargo.lock', 'crates.io'],
      ['Gemfile.lock', 'RubyGems'],
      ['poetry.lock', 'PyPI'],
      ['Pipfile.lock', 'PyPI'],
    ],
    'OSV ecosystem names are matched literally by the API — "cargo", "rubygems" or ' +
    '"pypi" are not errors, they return an empty result set, which records every ' +
    'app in that ecosystem as clean');
  for (const m of MANIFESTS) assert.equal(typeof m.parse, 'function', `${m.file} has no parser`);
});

test('two manifests may share one ecosystem', () => {
  // poetry.lock and Pipfile.lock are both PyPI. The table is keyed by FILE, not
  // by ecosystem, which is what lets a second Python packaging tool be one row.
  const pypi = MANIFESTS.filter(m => m.ecosystem === 'PyPI').map(m => m.file);
  assert.deepEqual(pypi, ['poetry.lock', 'Pipfile.lock']);
});

test('parseManifest dispatches on the filename when no row is passed', () => {
  const path = fixture('Cargo.lock', CARGO_LOCK);
  assert.deepEqual(parse(path), parse(path, MANIFESTS.find(m => m.file === 'Cargo.lock')));
});

test('an unrecognised filename throws rather than returning nothing', () => {
  const path = fixture('requirements.txt', 'django>=4.2\nrequests\n');
  assert.throws(() => parseManifest(path), /no parser for requirements.txt/,
    'an unreadable manifest returned a package list. requirements.txt pins nothing — ' +
    'guessing a version from ">=4.2" answers about a release that may not be installed');
});

test('the recorded error names the manifest that failed', () => {
  // An app can have several manifests. "Unexpected token" on its own does not
  // tell the person reading the scan row which file to open.
  const path = fixture('Pipfile.lock', '{ not json');
  assert.throws(() => parseManifest(path), /^Error: Pipfile\.lock: /);
});

// ---------------------------------------------------------------------------
// npm — generated by `npm install --package-lock-only`, not hand-written
// ---------------------------------------------------------------------------
//
// Produced by npm 10 for a root with a workspace, an aliased dependency
// (mylodash@npm:lodash@4.17.15) and a nested duplicate (async pulls its own
// lodash beside the root's lodash@3). Every trap in one real file.
const NPM_LOCK = JSON.stringify({
  name: 'fixture-root',
  version: '1.0.0',
  lockfileVersion: 3,
  requires: true,
  packages: {
    '': {
      name: 'fixture-root',
      version: '1.0.0',
      workspaces: ['packages/*'],
      dependencies: { async: '2.6.4', lodash: '3.10.1', mylodash: 'npm:lodash@4.17.15' },
    },
    'node_modules/@fixture/design-system': { resolved: 'packages/design-system', link: true },
    'node_modules/async': {
      version: '2.6.4',
      resolved: 'https://registry.npmjs.org/async/-/async-2.6.4.tgz',
      license: 'MIT',
      dependencies: { lodash: '^4.17.14' },
    },
    'node_modules/async/node_modules/lodash': {
      version: '4.18.1',
      resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.18.1.tgz',
      license: 'MIT',
    },
    'node_modules/lodash': {
      version: '3.10.1',
      resolved: 'https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz',
      license: 'MIT',
    },
    'node_modules/mylodash': {
      name: 'lodash',
      version: '4.17.15',
      resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz',
      license: 'MIT',
    },
    'packages/design-system': { name: '@fixture/design-system', version: '3.2.1' },
  },
}, null, 2);

test('a real npm lockfile yields only published packages, under their real names', () => {
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.deepEqual(idsOf(pkgs),
    ['async@2.6.4', 'lodash@3.10.1', 'lodash@4.17.15', 'lodash@4.18.1'],
    'the query set is not the published dependency set');
});

test('an aliased dependency is queried under the package name, not the alias', () => {
  // `npm i mylodash@npm:lodash@4.17.15` keys the entry by its INSTALL PATH.
  // OSV has never heard of "mylodash", so it answers clean and a lodash with
  // six advisories against it is recorded green. npm ships aliases itself —
  // string-width-cjs and strip-ansi-cjs arrive through cliui/wrap-ansi — so
  // this is not an exotic case.
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.ok(pkgs.some(p => p.name === 'lodash' && p.version === '4.17.15'),
    'the aliased lodash@4.17.15 was not queried under the name lodash');
  assert.ok(!pkgs.some(p => p.name === 'mylodash'),
    'the alias "mylodash" was sent to OSV — no registry has it, so the answer is a ' +
    'guaranteed false clean for a package with known advisories');
});

test('the root and the workspace member are not dependencies', () => {
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'fixture-root'),
    'the "" entry is the app itself and is published nowhere');
  // "packages/design-system" carries a real version and is NOT under
  // node_modules, so a parser that slices a fixed 13 characters off every key
  // reports a dependency named "esign-system" — plausible enough in a report,
  // and matching nothing in OSV.
  assert.ok(!pkgs.some(p => p.name.includes('design-system')),
    'the workspace member reached the query set');
  assert.ok(!pkgs.some(p => p.name.includes('/') && !p.name.startsWith('@')),
    'a package name still carries a path fragment; only a scoped name may contain a slash');
});

test('a nested dependency is named for the last node_modules segment', () => {
  const pkgs = parse(fixture('package-lock.json', NPM_LOCK));
  assert.ok(pkgs.some(p => p.name === 'lodash' && p.version === '4.18.1'),
    'the nested async/node_modules/lodash was named after its path — "async/lodash" ' +
    'is not a package, so OSV answers "no vulnerabilities"');
});

test('an npm v1 lockfile is an error, not an empty clean scan', () => {
  const path = fixture('package-lock.json',
    JSON.stringify({ lockfileVersion: 1, dependencies: { lodash: { version: '4.17.15' } } }));
  assert.throws(() => parseManifest(path), /lockfileVersion 1/,
    'a v1 lockfile parsed to zero packages instead of throwing, which records a clean ' +
    'bill of health for a file nothing ever read');
});

// ---------------------------------------------------------------------------
// Go
// ---------------------------------------------------------------------------
//
// Real go.sum lines: every module gets a zip hash and a /go.mod hash, module
// paths carry a /vN suffix from v2 on, and versions come in three shapes —
// plain, +incompatible, and a pseudo-version for an untagged commit.
const GO_SUM = `github.com/bytedance/sonic v1.9.1 h1:6iJ6NqdoxCDr6mbY8h18oSO+cShGSMRGCEo7F2h0x8s=
github.com/bytedance/sonic v1.9.1/go.mod h1:i736AoUSYgA8oJ0G7iZjNgnfC2LtQL9U6bZ0BpmB2mI=
github.com/docker/docker v20.10.0+incompatible h1:JcmoK6Wg4vNv7pdrxTUQZ2q0aE1cCRHNIvJmqSMKPmM=
github.com/docker/docker v20.10.0+incompatible/go.mod h1:eEKB0N0r5NX/I1kEveEz05bcu8tLC/8azJZsviup8Sk=
github.com/gin-gonic/gin v1.9.1 h1:4idEAncQnU5cB7BeOkPtxjfCSye0AAm1R0RVIqJ+Jmg=
github.com/gin-gonic/gin v1.9.1/go.mod h1:hPrL7YrpYKXt5YId3A/Tnip5kqbEAP+KLuI3SUcPTeU=
github.com/go-playground/validator/v10 v10.14.0 h1:vgvQWe3XCz3gIeFDm/HnTIbj6UGmg/+t63MyGU2n5js=
github.com/go-playground/validator/v10 v10.14.0/go.mod h1:9iXMNT7sEkjXb0I+enO7QXmzG6QCsPWY4zveKFVRSyU=
github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8 h1:0A+M6Uqn+Eje4kHMK80dtF3JCXC4ykBgQG4Fe06QRhQ=
golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
`;

test('go.sum reports one package per module, not one per hash line', () => {
  const pkgs = parse(fixture('go.sum', GO_SUM));
  assert.deepEqual(idsOf(pkgs), [
    'github.com/bytedance/sonic@v1.9.1',
    'github.com/docker/docker@v20.10.0+incompatible',
    'github.com/gin-gonic/gin@v1.9.1',
    'github.com/go-playground/validator/v10@v10.14.0',
    'golang.org/x/sys@v0.0.0-20220715151400-c0bba94af5f8',
  ], 'the /go.mod twin is a hash of the manifest, not a release. Reported as a package ' +
     'it asks OSV about version "v1.9.1/go.mod", which matches no range and answers clean');
});

test('a module present only as a /go.mod hash is not invented as a package', () => {
  // stretchr/objx appears in the graph for version resolution but is not in the
  // build, so go.sum has only its go.mod hash. Reporting it at version
  // "v0.1.0/go.mod" is a query slot spent on a string no advisory can match.
  const pkgs = parse(fixture('go.sum', GO_SUM));
  assert.ok(!pkgs.some(p => p.name.includes('objx')),
    'a go.mod-only module was reported, and at a version that does not exist');
  assert.ok(!pkgs.some(p => p.version.includes('/')),
    'a version still carries the /go.mod suffix');
});

test('+incompatible, pseudo-versions and /vN module paths survive verbatim', () => {
  // Measured, not assumed: github.com/docker/docker returns the same 35
  // advisories for v20.10.0+incompatible, 20.10.0+incompatible, v20.10.0 and
  // 20.10.0, so OSV normalises the Go form and the least transformation here is
  // also the safest. The +incompatible suffix appears inside OSV's own Go
  // advisory ranges (GO-2024-3005 opens at "20.10.0+incompatible"), so stripping
  // it would be editing a string the advisories themselves use.
  const pkgs = parse(fixture('go.sum', GO_SUM));
  const byName = Object.fromEntries(pkgs.map(p => [p.name, p.version]));
  assert.equal(byName['github.com/docker/docker'], 'v20.10.0+incompatible');
  assert.equal(byName['golang.org/x/sys'], 'v0.0.0-20220715151400-c0bba94af5f8');
  assert.equal(byName['github.com/go-playground/validator/v10'], 'v10.14.0',
    'the /v10 major-version suffix is part of the module path OSV indexes; dropping it ' +
    'asks about a different module');
});

test('a go.sum line that is not "module version hash" throws', () => {
  const path = fixture('go.sum', 'github.com/gin-gonic/gin v1.9.1\n');
  assert.throws(() => parseManifest(path), /go\.sum: line 1/,
    'a truncated go.sum line was skipped. Skipping means the module is never queried, ' +
    'which is indistinguishable from the module being clean');
});

test('a repeated module@version is queried once', () => {
  const pkgs = parse(fixture('go.sum', GO_SUM + GO_SUM));
  assert.equal(pkgs.length, 5, 'duplicate module lines became duplicate OSV queries');
});

// ---------------------------------------------------------------------------
// Rust
// ---------------------------------------------------------------------------
//
// Cargo writes the local crate as a [[package]] with no `source`, and parks
// unused [patch] entries in [[patch.unused]] blocks that carry name and version
// exactly like a real package does.
const CARGO_LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my-service"
version = "0.1.0"
dependencies = [
 "libc",
 "time",
]

[[package]]
name = "libc"
version = "0.2.147"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "b4668fb0ea861c1df094127ac5f1da3409a82116a4ba74fca2e58ef927159bb3"

[[package]]
name = "time"
version = "0.2.22"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "55b7151c9065e80917fbf285d9a5d1432f60db41d170ccafc749a136dcd0aeda"
dependencies = [
 "libc",
]

[[patch.unused]]
name = "winapi"
version = "0.4.0"

[metadata]
"checksum aho-corasick 0.7.18 (registry+https://github.com/rust-lang/crates.io-index)" = "1e37cfd5e7657ada45f742d6e99ca5788580b5c529dc78faf11ece6dc702656f"
`;

test('Cargo.lock reports registry crates and not the local crate', () => {
  const pkgs = parse(fixture('Cargo.lock', CARGO_LOCK));
  assert.deepEqual(idsOf(pkgs), ['libc@0.2.147', 'time@0.2.22'],
    'the workspace/root crate has no `source` because Cargo did not fetch it — it is ' +
    'published nowhere, so a query either matches nothing or matches an unrelated ' +
    'crate that happens to share the name');
});

test('a [[patch.unused]] block is neither a package nor a rename of the last one', () => {
  // It carries `name` and `version` at the same nesting a package does. A
  // reader that does not namespace keys by their table overwrites the previous
  // package's identity with winapi@0.4.0 — time 0.2.22, which has two
  // advisories against it (measured), silently becomes a crate that has none.
  const pkgs = parse(fixture('Cargo.lock', CARGO_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'winapi'), '[[patch.unused]] became a package');
  assert.ok(pkgs.some(p => p.name === 'time' && p.version === '0.2.22'),
    'the last real package lost its identity to the trailing [[patch.unused]] block');
});

test('a [[package]] with no version throws rather than being dropped', () => {
  const path = fixture('Cargo.lock', '[[package]]\nname = "libc"\nsource = "registry+x"\n');
  assert.throws(() => parseManifest(path), /Cargo\.lock: \[\[package\]\] at line 1 has no version/);
});

// ---------------------------------------------------------------------------
// Ruby
// ---------------------------------------------------------------------------
//
// The GEM specs block is indentation-sensitive: 4 spaces is an installed gem,
// 6 spaces is one of its dependency constraints. GIT and PATH sections repeat
// the same shape for gems that did not come from rubygems.org.
const GEMFILE_LOCK = `GIT
  remote: https://github.com/rails/rails.git
  revision: 6f0d1ca4b1e0bc94e0d8f6e1b4b0f1e7a0d0c0b0
  specs:
    railties (7.1.0.alpha)
      actionpack (= 7.1.0.alpha)

PATH
  remote: engines/billing
  specs:
    billing (0.1.0)
      rack

GEM
  remote: https://rubygems.org/
  specs:
    actionpack (7.0.4)
      actionview (= 7.0.4)
      activesupport (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
    nokogiri (1.13.5-x86_64-linux)
      racc (~> 1.4)
    racc (1.6.0)
    rack (2.2.4)
    rails (7.1.0.beta1)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  nokogiri
  railties!

CHECKSUMS
  rack (2.2.4) sha256=d1f0e3e8b7ee0e0f0c0a0e0b0d0c0a0e0b0d0c0a0e0b0d0c0a0e0b0d0c0a0e0b

BUNDLED WITH
   2.4.10
`;

test('only the 4-space GEM entries are installed gems', () => {
  const pkgs = parse(fixture('Gemfile.lock', GEMFILE_LOCK));
  assert.deepEqual(idsOf(pkgs), [
    'actionpack@7.0.4', 'nokogiri@1.13.5', 'racc@1.6.0', 'rack@2.2.4', 'rails@7.1.0.beta1',
  ], 'the specs block was read without regard to indentation');
});

test('a 6-space dependency constraint is not a gem at that version', () => {
  // `      rack (~> 2.0, >= 2.2.0)` is what actionpack ASKS FOR, not what is
  // installed. Read as a gem it queries rack at version "~> 2.0, >= 2.2.0",
  // which matches nothing — and it displaces the real rack 2.2.4 in any
  // dedupe keyed on name.
  const pkgs = parse(fixture('Gemfile.lock', GEMFILE_LOCK));
  assert.ok(!pkgs.some(p => /[~>=,]/.test(p.version)),
    'a dependency constraint was recorded as an installed version');
  assert.ok(!pkgs.some(p => p.name === 'actionview'),
    'actionview appears only as a constraint under actionpack and is not installed here');
});

test('GIT and PATH sections are not rubygems.org packages', () => {
  const pkgs = parse(fixture('Gemfile.lock', GEMFILE_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'railties'),
    'a gem resolved from a git checkout was queried against RubyGems, where its version ' +
    'need not correspond to any published release');
  assert.ok(!pkgs.some(p => p.name === 'billing'),
    'a PATH gem is local to the app and is published nowhere');
});

test('the platform suffix is stripped and the dotted prerelease is not', () => {
  // Measured against the live OSV API, and the reason this line exists:
  //   activerecord 7.0.0              -> 4 advisories
  //   activerecord 7.0.0-x86_64-linux -> 1 advisory
  // The three that vanish are the ones whose range opens at introduced 7.0.0 —
  // Ruby reads the hyphen as a prerelease separator, so the suffixed string
  // sorts BELOW the plain version and falls outside the range. Three silent
  // false cleans from one platform suffix. Ruby's own prereleases use dots
  // (7.1.0.beta1), so cutting at the first hyphen only ever removes a platform.
  const byName = Object.fromEntries(parse(fixture('Gemfile.lock', GEMFILE_LOCK))
    .map(p => [p.name, p.version]));
  assert.equal(byName.nokogiri, '1.13.5',
    'the platform suffix was left on the version, which moves it below every ' +
    '"introduced" boundary and hides the advisories that open there');
  assert.equal(byName.rails, '7.1.0.beta1',
    'a dotted Ruby prerelease was truncated — that is a different version');
});

test('a 4-space line inside GEM specs that is not "name (version)" throws', () => {
  const path = fixture('Gemfile.lock', 'GEM\n  remote: https://rubygems.org/\n  specs:\n    rack 2.2.4\n');
  assert.throws(() => parseManifest(path), /Gemfile\.lock: line 4/,
    'an unparseable spec line was skipped, so the gem is never queried and the app ' +
    'reads as clean');
});

// ---------------------------------------------------------------------------
// Python — poetry
// ---------------------------------------------------------------------------
//
// Poetry 1.5 format: each [[package]] is followed by nested tables —
// [package.dependencies], [package.extras], [package.source] — whose lines
// contain `=` and sit at the same indentation as the block's own keys.
const POETRY_LOCK = `# This file is automatically @generated by Poetry 1.5.1 and should not be changed by hand.

[[package]]
name = "certifi"
version = "2023.7.22"
description = "Python package for providing Mozilla's CA Bundle."
optional = false
python-versions = ">=3.6"
files = [
    {file = "certifi-2023.7.22-py3-none-any.whl", hash = "sha256:92d6037539857d8206b8f6ae472e8b77db8dd2497"},
    {file = "certifi-2023.7.22.tar.gz", hash = "sha256:539cc1d13202e33ca466e88b2807e29f4c13049d"},
]

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = []

[package.dependencies]
certifi = ">=2017.4.17"
urllib3 = ">=1.21.1,<3"

[package.extras]
socks = ["PySocks (>=1.5.6,!=1.5.7)"]

[[package]]
name = "billing"
version = "0.1.0"
description = "The app's own engine"
optional = false
python-versions = "^3.11"
files = []
develop = true

[package.source]
type = "directory"
url = "engines/billing"

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "8b0c8a0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e"
`;

test('poetry.lock reports the packages and not their constraints', () => {
  const pkgs = parse(fixture('poetry.lock', POETRY_LOCK));
  assert.deepEqual(idsOf(pkgs), ['certifi@2023.7.22', 'requests@2.31.0'],
    '[package.dependencies] lists what a package ASKS FOR — urllib3 ">=1.21.1,<3" is a ' +
    'range, not an installed version, and there is no way to query it');
  assert.ok(!pkgs.some(p => p.name === 'urllib3'),
    'a constraint under [package.dependencies] became a package');
});

test('a directory source is the app itself, not a PyPI package', () => {
  // The exclusion depends on reading `type` under [package.source] rather than
  // as a block-level key. A reader that flattens nested tables never sees the
  // namespaced key, keeps the block, and queries PyPI for "billing" 0.1.0 —
  // where an unrelated project of that name may well answer.
  const pkgs = parse(fixture('poetry.lock', POETRY_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'billing'),
    'a path dependency was queried against PyPI');
});

test('a poetry package with no version throws', () => {
  const path = fixture('poetry.lock', '[[package]]\nname = "certifi"\noptional = false\n');
  assert.throws(() => parseManifest(path), /poetry\.lock: \[\[package\]\] at line 1 has no version/);
});

// ---------------------------------------------------------------------------
// Python — pipenv
// ---------------------------------------------------------------------------

const PIPFILE_LOCK = JSON.stringify({
  _meta: {
    hash: { sha256: 'aa0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e' },
    'pipfile-spec': 6,
    requires: { python_version: '3.11' },
    sources: [{ name: 'pypi', url: 'https://pypi.org/simple', verify_ssl: true }],
  },
  default: {
    certifi: { hashes: ['sha256:92d60375'], markers: "python_version >= '3.6'", version: '==2023.7.22' },
    requests: { hashes: ['sha256:942c5a75'], index: 'pypi', version: '==2.31.0' },
    'internal-lib': { git: 'https://github.com/example/internal-lib.git', ref: '6f0d1ca4b1e0' },
  },
  develop: {
    pytest: { hashes: ['sha256:b4bf8c45'], version: '==7.4.0' },
  },
}, null, 2);

test('Pipfile.lock covers default and develop, with the == pin removed', () => {
  const pkgs = parse(fixture('Pipfile.lock', PIPFILE_LOCK));
  assert.deepEqual(idsOf(pkgs), ['certifi@2023.7.22', 'pytest@7.4.0', 'requests@2.31.0'],
    'develop dependencies run in CI and ship in dev images; leaving them out is the ' +
    'under-report this feature exists to prevent');
  assert.ok(!pkgs.some(p => p.version.startsWith('=')),
    'the "==" pin was passed through as part of the version, which matches no range');
});

test('_meta is not mistaken for a package section', () => {
  const pkgs = parse(fixture('Pipfile.lock', PIPFILE_LOCK));
  assert.ok(!pkgs.some(p => ['hash', 'sources', 'requires', 'pipfile-spec'].includes(p.name)));
});

test('a git requirement pins a ref, not a release, and is left out', () => {
  const pkgs = parse(fixture('Pipfile.lock', PIPFILE_LOCK));
  assert.ok(!pkgs.some(p => p.name === 'internal-lib'),
    'a VCS requirement has no version; inventing one is the requirements.txt mistake');
});

test('an unpinned Pipfile.lock entry is an error, not a guess', () => {
  // pipenv always writes "==<version>". Anything else means the file is not
  // what it claims to be, and a range has no single installed version — an
  // 'error' is visible and gets fixed, a quietly dropped package is not.
  const path = fixture('Pipfile.lock', JSON.stringify({ default: { django: { version: '>=4.2' } } }));
  assert.throws(() => parseManifest(path), /"django" in default is not pinned/,
    'a range was accepted as a version, which answers confidently about a release ' +
    'that may not be installed');
});

test('a JSON file with no default or develop section is not a Pipfile.lock', () => {
  const path = fixture('Pipfile.lock', JSON.stringify({ _meta: { 'pipfile-spec': 6 } }));
  assert.throws(() => parseManifest(path), /no "default" or "develop" section/,
    'an unrecognised JSON file parsed to zero packages — a clean scan for a file ' +
    'nothing understood');
});

// ---------------------------------------------------------------------------
// the shape contract, across every parser
// ---------------------------------------------------------------------------

test('every package from every parser carries its table row ecosystem', () => {
  // The ecosystem travels WITH the package rather than being applied at query
  // time, which is what lets one scan mix ecosystems in a single OSV batch. A
  // parser that forgets it emits a package the asserter rejects.
  const cases = [
    ['package-lock.json', NPM_LOCK, 'npm'],
    ['go.sum', GO_SUM, 'Go'],
    ['Cargo.lock', CARGO_LOCK, 'crates.io'],
    ['Gemfile.lock', GEMFILE_LOCK, 'RubyGems'],
    ['poetry.lock', POETRY_LOCK, 'PyPI'],
    ['Pipfile.lock', PIPFILE_LOCK, 'PyPI'],
  ];
  for (const [file, contents, ecosystem] of cases) {
    const pkgs = parse(fixture(file, contents));
    assert.ok(pkgs.length > 0, `${file} parsed to nothing`);
    for (const p of pkgs) {
      assertPackage(p, file);
      assert.equal(p.ecosystem, ecosystem, `${file} emitted ecosystem ${p.ecosystem}`);
    }
  }
});
